# Generated by Django 4.2.4 on 2023-10-30 14:42

from django.db import migrations


def age_group_update(apps, schema_editor):
    person_model = apps.get_model('main_app', 'Person')

    all_persons = person_model.objects.all()

    for person in all_persons:
        if person.age <= 12:
            person.age_group = "Child"

        elif 13 <= person.age <= 17:
            person.age_group = "Teen"

        else:
            person.age_group = "Adult"


def reverse_age_group_update(apps, schema_editor):
    person_model = apps.get_model('main_app', 'Person')

    default_app_group = person_model._meta.get_field('age_group').default

    all_persons = person_model.objects.all()

    for person in all_persons:
        person.age_group = default_app_group

    person_model.objects.bulk_update(all_persons, ['age_group'])


class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0009_person'),
    ]

    operations = [
        migrations.RunPython(age_group_update, reverse_code=reverse_age_group_update)
    ]
