# Generated by Django 4.2.4 on 2023-11-24 15:26

from django.db import migrations
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=main_app.models.StudentIDField(default=1),
            preserve_default=False,
        ),
    ]
