# Generated by Django 4.2.4 on 2023-11-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_artifact'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
